version: 2
jobs:
  build:
    docker:
      - image: qawolf/qawolf:v0.7.0-alpha.1
        environment:
          # output artifacts
          QAW_DOM_PATH: /tmp/artifacts
          QAW_LOG_PATH: /tmp/artifacts
          QAW_VIDEO_PATH: /tmp/artifacts
          # parameterize tests
          FROM_AIRPORT: IND
          TO_AIRPORT: BOS
          DEPART_DATE: "3/26"
          RETURN_DATE: "4/20"
    steps:
      # checkout to include the .qawolf/ folder
      - checkout

      - run:
          command: qawolf test

      - store_artifacts:
          path: /tmp/artifacts
